### ISSUE TITLE
Unable to train Any Pixor Model Nor Run the Provided Model

### ISSUE THREAD

**Issue by xavierallem** [DerrickXuNu/OpenCOOD#154]
Hello, 
Thank you for the great work you guys have done. I followed the step that showed me how to train. However, I get this error when I try to train any pixor model. I get these errors. I haven't changed any parameters.  

**Pixor_intermediate_fusion**

```bash
Not using distributed mode
-----------------Dataset Building------------------
---------------Creating Model------------------
optimizer method is: <class 'torch.optim.adam.Adam'>
not supported lr scheduler
```

**Pixor_Late_Fusion**

```bash
 File "/home/xavierallem/Opencood_testing/OpenCOOD/opencood/data_utils/datasets/__init__.py", line 38, in build_dataset
    train=train
  File "/home/xavierallem/Opencood_testing/OpenCOOD/opencood/data_utils/datasets/late_fusion_dataset.py", line 34, in __init__
    super(LateFusionDataset, self).__init__(params, visualize, train)
  File "/home/xavierallem/OpenCOOD/opencood/data_utils/datasets/basedataset.py", line 67, in __init__
    self.data_augmentor = DataAugmentor(params['data_augment'],
KeyError: 'data_augment'
```

**Pixor_Early_fusion** 

```bash
Not using distributed mode
-----------------Dataset Building------------------
---------------Creating Model------------------
optimizer method is: <class 'torch.optim.adam.Adam'>
not supported lr scheduler
```

**Steps performed**
- Export the Config file with changed dataset path (Any type pf fusion)
 ```bash 
python opencood/tools/train.py --hypes_yaml ${CONFIG_FILE}
```

**Model Inference** 

Also while running the Model from here -> [Link](https://ucla.app.box.com/v/UCLA-MobilityLab-OPV2V/file/1621127209949)

```bash
Dataset Building
1980 samples found.
Creating Model
Loading Model from checkpoint
resuming by loading epoch 10000
0it [00:00, ?it/s]/home/xavierallem/miniconda3/envs/opencood/lib/python3.7/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/xavierallem/miniconda3/envs/opencood/lib/python3.7/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
0it [00:12, ?it/s]
Traceback (most recent call last):
  File "opencood/tools/inference.py", line 208, in <module>
    main()
  File "opencood/tools/inference.py", line 175, in main
    mode='constant'
  File "/home/xavierallem/Opencood_testing/OpenCOOD/opencood/visualization/vis_utils.py", line 508, in visualize_inference_sample_dataloader
    pred_o3d_box = bbx2linset(pred_box_tensor, color=(1, 0, 0))
  File "/home/xavierallem/Opencood_testing/OpenCOOD/opencood/visualization/vis_utils.py", line 64, in bbx2linset
    line_set.points = o3d.utility.Vector3dVector(bbx)
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

**Steps performed**
- Export the model dir with changed dataset path (Any type pf fusion)
- Export Early Stratergy
 ```bash  
python opencood/tools/inference.py --model_dir ${CHECKPOINT_FOLDER} --fusion_method ${FUSION_STRATEGY} --show_sequence
 ```

Can you Please help me through this? Is there any additional step That I need to follow?

**Comment by wkyd** [comment]
可以请教一下您运行这个项目的步骤吗，请问您是在windows上还是Ubuntu上

**Comment by shellby798** [comment]
train_utils中的第229行中“exponential”首字母是小写，改成大写就行了
