### ISSUE TITLE
What is your experiment environment?

### ISSUE THREAD

**Issue by susanbao** [DerrickXuNu/OpenCOOD#18]
When I tried to train for SECOND. I meet this problem:
Traceback (most recent call last):
  File "opencood/tools/train.py", line 138, in <module>
    main()
  File "opencood/tools/train.py", line 100, in main
    ouput_dict = model(batch_data['ego'])
  File "/home/sas20048/anaconda3/envs/opencood/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sas20048/code/OpenCOOD/opencood/models/second_intermediate.py", line 45, in forward
    batch_dict = self.backbone_3d(batch_dict)
  File "/home/sas20048/anaconda3/envs/opencood/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sas20048/code/OpenCOOD/opencood/models/sub_modules/sparse_backbone_3d.py", line 106, in forward
    x = self.conv_input(input_sp_tensor)
  File "/home/sas20048/anaconda3/envs/opencood/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sas20048/anaconda3/envs/opencood/lib/python3.7/site-packages/spconv/modules.py", line 134, in forward
    input = module(input)
  File "/home/sas20048/anaconda3/envs/opencood/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sas20048/anaconda3/envs/opencood/lib/python3.7/site-packages/spconv/conv.py", line 181, in forward
    use_hash=self.use_hash)
  File "/home/sas20048/anaconda3/envs/opencood/lib/python3.7/site-packages/spconv/ops.py", line 95, in get_indice_pairs
    int(use_hash))
ValueError: /home/sas20048/code/spconv/src/spconv/spconv_ops.cc 87
unknown device type

I found this issue https://github.com/traveller59/spconv/issues/58 and tried their method. But failed.

So I think maybe my cuda version or pytorch version mismatches spconv1.2.1. So could you tell me your experiment environment information, especially for cuda and pytorch? Thanks.

I used cuda 10.1, pytorch 1.10.0.

**Comment by susanbao** [comment]
> When I tried to train for SECOND. I meet this problem: Traceback (most recent call last): File "opencood/tools/train.py", line 138, in main() File "opencood/tools/train.py", line 100, in main ouput_dict = model(batch_data['ego']) File "/home/sas20048/anaconda3/envs/opencood/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/sas20048/code/OpenCOOD/opencood/models/second_intermediate.py", line 45, in forward batch_dict = self.backbone_3d(batch_dict) File "/home/sas20048/anaconda3/envs/opencood/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/sas20048/code/OpenCOOD/opencood/models/sub_modules/sparse_backbone_3d.py", line 106, in forward x = self.conv_input(input_sp_tensor) File "/home/sas20048/anaconda3/envs/opencood/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/sas20048/anaconda3/envs/opencood/lib/python3.7/site-packages/spconv/modules.py", line 134, in forward input = module(input) File "/home/sas20048/anaconda3/envs/opencood/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/sas20048/anaconda3/envs/opencood/lib/python3.7/site-packages/spconv/conv.py", line 181, in forward use_hash=self.use_hash) File "/home/sas20048/anaconda3/envs/opencood/lib/python3.7/site-packages/spconv/ops.py", line 95, in get_indice_pairs int(use_hash)) ValueError: /home/sas20048/code/spconv/src/spconv/spconv_ops.cc 87 unknown device type
> 
> I found this issue [traveller59/spconv#58](https://github.com/traveller59/spconv/issues/58) and tried their method. But failed.
> 
> So I think maybe my cuda version or pytorch version mismatches spconv1.2.1. So could you tell me your experiment environment information, especially for cuda and pytorch? Thanks.

I used cuda 10.1, pytorch1.10.0.

**Comment by DerrickXuNu** [comment]
For sure! I know spconv can have some issues and give you a hard time....
OS: Ubuntu 1804
Pytorch: 1.10.2
CUDA version: Cuda compilation tools, release 11.1, V11.1.105

Can you run pointpillar or voxelnet? Is it just SECOND?

**Comment by susanbao** [comment]
> 

I just met this problem on SECOND. the other three models works fine.

**Comment by DerrickXuNu** [comment]
Ok,as this is mainly an issue related to spconv, I will close it.
