### ISSUE TITLE
some error when test the model

### ISSUE THREAD

**Issue by kanglang123** [DerrickXuNu/OpenCOOD#43]
python opencood/tools/inference.py --model_dir /home/robot/下载/pointpillar_v2vnet/v2vnet --fusion_method intermediate
Dataset Building
550 samples found.
Creating Model
Loading Model from checkpoint
resuming by loading epoch 83
0it [00:01, ?it/s]
Traceback (most recent call last):
  File "opencood/tools/inference.py", line 204, in <module>
    main()
  File "opencood/tools/inference.py", line 100, in main
    for i, batch_data in tqdm(enumerate(data_loader)):
  File "/home/robot/miniconda3/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/robot/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/robot/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/robot/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/robot/miniconda3/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/robot/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/robot/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/robot/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/robot/OpenCOOD1/opencood/data_utils/datasets/intermediate_fusion_dataset.py", line 96, in __getitem__
    ego_lidar_pose)
  File "/home/robot/OpenCOOD1/opencood/data_utils/datasets/intermediate_fusion_dataset.py", line 191, in get_item_single_car
    processed_lidar = self.pre_processor.preprocess(lidar_np)
  File "/home/robot/OpenCOOD1/opencood/data_utils/pre_processor/sp_voxel_preprocessor.py", line 49, in preprocess
    voxel_output = self.voxel_generator.generate(pcd_np)
  File "/home/robot/miniconda3/lib/python3.7/site-packages/spconv/utils/__init__.py", line 173, in generate
    or self._max_voxels, self._full_mean)
  File "/home/robot/miniconda3/lib/python3.7/site-packages/spconv/utils/__init__.py", line 69, in points_to_voxel
    assert block_filtering is False
AssertionError

**Comment by DerrickXuNu** [comment]
This is likely caused by the spconv version. What is your spconv version?
